--Данные для БД "Номенклатура" (Nomenclature)
USE Nomenclature;

INSERT INTO Types VALUES ('Изделие')
INSERT INTO Types VALUES ('Узел')
INSERT INTO Types VALUES ('Деталь')
INSERT INTO Types VALUES ('Материал')

INSERT INTO Warehouses VALUES ('Склад №1','Оренбургская область, город Луховицы, спуск Будапештсткая, 96')
INSERT INTO Warehouses VALUES ('Склад №2','Магаданская область, город Талдом, проезд Космонавтов, 62')
INSERT INTO Warehouses VALUES ('Склад №3', 'Оренбургская область, город Истра, ул. Гагарина, 52')

INSERT INTO Materials VALUES ('Шурупы (60 шт)','Отсутствует',4)
INSERT INTO Materials VALUES ('Алюминий (100x100)','Отсутствует',4)
INSERT INTO Materials VALUES ('Доски (90x90x2)','Отсутствует',4)
INSERT INTO Materials VALUES ('Пластмасса (100x100)','Отсутствует',4)

INSERT INTO Materials VALUES ('Ручка','ДБПС 0004.01.01.204',3)
INSERT INTO Materials VALUES ('Колёсико','ДБПС 0004.01.02.207',3)

INSERT INTO Materials VALUES ('Ножка стола','ДБПС 0004.01.22.207',2)
INSERT INTO Materials VALUES ('Верхняя часть стола','ДБПС 0005.01.22.207',2)
INSERT INTO Materials VALUES ('Стенка тумбочки','ДБПС 0006.01.22.207',2)
INSERT INTO Materials VALUES ('Полка (30х20х90)','ДБПС 0006.02.22.207',2)

INSERT INTO Materials VALUES ('Стол','ДБПС 0006.01.23.212',1)
INSERT INTO Materials VALUES ('Тумбочка','ДБПС 0006.01.23.213',1)

INSERT INTO Hierarchy VALUES (5,2,1)
INSERT INTO Hierarchy VALUES (5,3,1)
INSERT INTO Hierarchy VALUES (6,2,1)
INSERT INTO Hierarchy VALUES (6,3,1)
INSERT INTO Hierarchy VALUES (7,2,1)
INSERT INTO Hierarchy VALUES (7,3,5)
INSERT INTO Hierarchy VALUES (8,2,4)
INSERT INTO Hierarchy VALUES (8,3,4)
INSERT INTO Hierarchy VALUES (9,2,4)
INSERT INTO Hierarchy VALUES (9,3,1)
INSERT INTO Hierarchy VALUES (10,2,4)
INSERT INTO Hierarchy VALUES (10,3,3)
INSERT INTO Hierarchy VALUES (10,5,1)
INSERT INTO Hierarchy VALUES (11,7,4)
INSERT INTO Hierarchy VALUES (11,8,1)
INSERT INTO Hierarchy VALUES (12,9,5)
INSERT INTO Hierarchy VALUES (12,10,4)

INSERT INTO Storage VALUES (1,1,25)
INSERT INTO Storage VALUES (2,2,35)
INSERT INTO Storage VALUES (1,3,15)
INSERT INTO Storage VALUES (3,4,29)
INSERT INTO Storage VALUES (2,5,13)
INSERT INTO Storage VALUES (1,6,20)
INSERT INTO Storage VALUES (3,1,40)
INSERT INTO Storage VALUES (1,8,16)
INSERT INTO Storage VALUES (2,9,4)
INSERT INTO Storage VALUES (1,10,7)
INSERT INTO Storage VALUES (2,11,1)
INSERT INTO Storage VALUES (1,12,3)
INSERT INTO Storage VALUES (3,2,21)
INSERT INTO Storage VALUES (3,3,26)
INSERT INTO Storage VALUES (1,4,10)